services:
  influxdb3-core: # Setup The InfluxDB 3 Core Instance
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 127.0.0.1:8181:8181 # Bind port to localhost only for security
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - influxdb_data:/var/lib/influxdb3
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Authorization: Bearer ${INFLUXDB_TOKEN}' http://localhost:8181/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - mynet

  explorer: # Explorer Is a Web UI for InfluxDB 3
    image: influxdata/influxdb3-ui
    container_name: influxdb3-explorer
    command: ["--mode=admin"]
    ports:
      - "127.0.0.1:8888:80"      # UI Web interface
      - "127.0.0.1:8889:8888"    # FlightSQL / gRPC API endpoint
    restart: unless-stopped
    #environment:
    #  - INFLUXDB_URL=http://influxdb3-core:8181
    #  - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - mynet

  cloudflared: # Remote Access to Exolrer
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - mynet

volumes:
  influxdb_data:

networks:
  mynet:


